### ISSUE TITLE
questions on dependency we install by `apt-get`

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-readme#5]
Two questions.

## Maybe we should revise README

In the README, we mentioned:
```
Install related packages including cmake git build-essential libssl-dev libgmp-dev (for Linux), ..., or use this script.
```

Actually, boost is needed for Linux. But as the script shows, that needs a little bit efforts:
```
        sudo apt-get install -y software-properties-common
	sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
	sudo add-apt-repository -y ppa:kojoley/boost
	sudo apt-get update
	sudo apt-get install -y cmake git build-essential libssl-dev libgmp-dev python 
	sudo apt-get install -y libboost1.58-dev
	sudo apt-get install -y libboost-{chrono,log,program-options,date-time,thread,system,filesystem,regex,test}1.58-dev
```

I think maybe we should tell the users to use the script instead? So `Install related packages including cmake git build-essential libssl-dev libgmp-dev (for Linux)` will be deleted.

## Maybe we should change the script

Any reason for using libboost 1.58 and cmake for ppa? As if someone is using newer version of Ubuntu, maybe he/she already has newer versions.

And adding ppa is always not the best solution.

For Ubuntu 16.04, `apt` can find libboost 1.58 from ubuntu official source, and cmake 3.51.

Do you have a minimal Ubuntu version requirement in minds?

**Comment by weikengchen** [comment]
and if `ppa` does not have the cmake or libboost for the corresponding ubuntu versions, it will fail.

For example, if I am running Ubuntu 18.04,  `apt` cannot find `libboost` and `cmake` from the ppa.

And every time the user runs `apt update`, the user is going to see 404 404...

**Comment by wangxiao1254** [comment]
I have the packages listed, because some people in linux do not use ubuntu distro.

**Comment by weikengchen** [comment]
Then we need to add `libboost` in the linux part.

Currently, `libboost-dev libboost-{chrono,log,program-options,date-time,thread,system,filesystem,regex,test}-dev` are not in that APT-GET command.

**Comment by wangxiao1254** [comment]
Thanks and done!!
