### ISSUE TITLE
How to install emp without root 

### ISSUE THREAD

**Issue by fedoraghi** [emp-toolkit/emp-readme#7]
Hi Xiao Wang, 

I want to install emp-ot on my working pc (linux) which I don't have root access. How to avoid `sudo make install` at https://github.com/emp-toolkit/emp-readme/blob/master/scripts/install_emp-ot.sh#L5.

I try `cmake . && make DESTDIR=.. all install` for relic and emp-tool. However, when I compile emp-ot with `cmake . CMAKE_SYSTEM_PREFIX_PATH=..`. I get a following error

1. CMAKE_FOLDER-NOTFOUND/cmake/common.cmake
2. CMAKE_FOLDER-NOTFOUND/cmake/source_of_randomness.cmake
3. CMAKE_FOLDER-NOTFOUND/cmake/threading.cmake
4. CMake Error at emp/emp-tool/cmake/emp-tool-config.cmake:2 (find_package)
5. Could not find a package configuration file provided by "relic"

**Comment by wangxiao1254** [comment]
You need to set the variable "CMAKE_INSTALL_PREFIX" when you cmake.

**Comment by farhadtaheri** [comment]
Hi 
I have the same problem when trying to run the Cmake command. 
how to set the `CMAKE_INSTALL_PREFIX` variable.

**Comment by wangxiao1254** [comment]
If your prefix is `/path/of/prefix`, then you can do `cmake -D CMAKE_INSTALL_PREFIX=/path/of/prefix .`

Some googling should help too.
