### ISSUE TITLE
install.py fails when adding -ag2pc

### ISSUE THREAD

**Issue by owenkaser** [emp-toolkit/emp-readme#8]
Install.py fails when  -ag2pc is added.  It fails with a complaint from cmake about missing add_test_with_lib  macro.

This macro was present in earlier versions of emp_tool/cmake/common.cmake but was removed in df9446c

As a workaround, I copied the previous macro into emp-ag2pc/CMakeLists.txt and 
   cmake .
   make
now complete.

**Comment by wangxiao1254** [comment]
just updated. Let's see if it works.

**Comment by owenkaser** [comment]
It works.  Thanks.
